baseURL = 'http://13.95.204.178/ministerioUnivesidades.grupoavalon.com/portal-web/'
publishDir = '../../xampp/htdocs/ministeriounivesidades.grupoavalon.com/portal-web/'
languageCode = 'en-us'
title = 'MINU'
defaultContentLanguage = 'es'
paginate = 5
navigationNewWindow = true
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[taxonomies]
  actor = 'actors'
[menu]
  [[menu.main]]
    identifier = "Ministerio"
    name = "Ministerio"
    url = "/ministerio/"
    weight = 1
    [menu.main.params]
        identifier = 'menu1'
 [[menu.main]]
    identifier = "Estructura"
    name = "Estructura y funciones"
    url = "/ministerio/estructura-y-funciones/"
    parent = "Ministerio"
    weight = 1
[[menu.main]]
    identifier = "Organismos"
    name = "Organismos"
    url = "/ministerio/organismos"
    parent = "Ministerio"
    weight = 2
  [[menu.main]]
    identifier = "Medidas_Estrategicas"
    name = "Medidas Estratégicas"
    url = "/"
    weight = 2
     [menu.main.params]
        identifier = 'menu2'

 [[menu.main]]
    identifier = "Becas y Ayudas al Estudio"
    name = "Becas y Ayudas al Estudio"
    url = "/medidas-estrategicas/becas-y-ayudas-al-estudio"
    parent = "Medidas_Estrategicas"
    weight = 1
 [[menu.main]]
    identifier = "Campus sostenible"
    name = "Campus sostenible"
    url = "/medidas-estrategicas/campus-sostenible"
    parent = "Medidas_Estrategicas"
    weight = 2
 [[menu.main]]
    identifier = "Equidad de género"
    name = "Equidad de género"
    url = "/medidas-estrategicas/equidad-de-genero"
    parent = "Medidas_Estrategicas"
    weight = 3
 [[menu.main]]
    identifier = "Estudio brecha salarial de género"
    name = "Estudio brecha salarial de género"
    url = "/medidas-estrategicas/estudio-brecha-salarial"
    parent = "Medidas_Estrategicas"
    weight = 4
 [[menu.main]]
    identifier = "La universidad frente al reto demográfico"
    name = "La universidad frente al reto demográfico"
    url = "/medidas-estrategicas/reto-demografico"
    parent = "Medidas_Estrategicas"
    weight = 5
[[menu.main]]
    identifier = "Precios públicos"
    name = "Precios públicos"
    url = "/medidas-estrategicas/precio-publico"
    parent = "Medidas_Estrategicas"
    weight = 6
[[menu.main]]
    identifier = "Plan estratégico de Subvenciones 2021"
    name = "Plan estratégico de Subvenciones 2021"
    url = "/medidas-estrategicas/plan-estrategico"
    parent = "Medidas_Estrategicas"
    weight = 7
[[menu.main]]
    identifier = "Plan de Recuperación y Resiliencia"
    name = "Plan de Recuperación y Resiliencia"
    # url = "https://planderecuperacion.gob.es/"
    url = "/medidas-estrategicas/plan-recuperacion"
    parent = "Medidas_Estrategicas"
    weight = 8
[[menu.main]]
    identifier = "Brexit"
    name = "Brexit"
    url = "/medidas-estrategicas/brexit"
    parent = "Medidas_Estrategicas"
    weight = 8
  [[menu.main]]
    identifier = "Tu_Administracion"
    name = "Tu Administración"
    weight = 3
    [menu.main.params]
        identifier = 'menu3'
[[menu.main]]
    name = "Registro, Legalizaciones y Credenciales"
    url = "/tu-administracion/registro-legalizaciones-y-credentiales/"
    parent = "Tu_Administracion"
    weight = 1

[[menu.main]]
    name = "Información y Atención al Ciudadano"
    url = "/tu-administracion/informacion-y-atencion-al-ciudadano"
    parent = "Tu_Administracion"
    weight = 2
[[menu.main]]
    identifier = "Sede electrónica"
    name = "Sede Electrónica"
    url = "https://universidades.sede.gob.es/"
    parent = "Tu_Administracion"
    weight = 3
    [menu.main.params]
        external_link = true
[[menu.main]]
    name = "Transparencia y Gobierno Abierto"
    url = "/tu-administracion/transparencia-y-gobierno-abierto"
    parent = "Tu_Administracion"
    weight = 4
[[menu.main]]
    name = "Perfil del contratante"
    url = "/tu-administracion/perfil-del-contratante"
    parent = "Tu_Administracion"
    weight = 5
[[menu.main]]
    name = "Protección de datos personales"
    url = "/tu-administracion/proteccion-de-datos-personales"
    parent = "Tu_Administracion"
    weight = 6
[[menu.main]]
    name = "Empleo público"
    url = "/tu-administracion/empleo-publico"
    parent = "Tu_Administracion"
    weight = 7

[[menu.main]]
    name = "Centro de documentación, Normativa y Publicaciones"
    url = "/tu-administracion/normativa/"
    parent = "Tu_Administracion"
    weight = 8

 [[menu.main]]
    identifier = "Sistema_Universitario"
    name = "Sistema Universitario"
    url = "/#"
    weight = 4
    [menu.main.params]
        identifier = 'menu4'
[[menu.main]]
    identifier = "Dónde estudiar"
    name = "Dónde estudiar"
    url = "/sistema-universitario/donde-estudiar"
    parent = "Sistema_Universitario"
    weight = 1
[[menu.main]]
    identifier = "Becas, ayudas y premios universitarios"
    name = "Becas, ayudas y premios universitarios"
    url = "/convocatorias/"
    parent = "Sistema_Universitario"
    weight = 2
[[menu.main]]
    identifier = "Gestión de títulos universitarios"
    name = "Gestión de títulos universitarios"
    url = "/sistema-universitario/gestion-de-titulos-universitarios"
    parent = "Sistema_Universitario"
    weight = 3
[[menu.main]]
    identifier = "Acreditación (Academia)"
    name = "Acreditación (Academia)"
    url = "http://www.aneca.es/Programas-de-evaluacion/Evaluacion-de-profesorado/ACADEMIA"
    parent = "Sistema_Universitario"
    weight = 4
    [menu.main.params]
        external_link = true
[[menu.main]]
    identifier = "Evaluación para la contratación del profesorado universitario"
    name = "Evaluación para la contratación del profesorado universitario"
    url = "https://universidades.sede.gob.es/pagina/index/directorio/Programa_PEP/"
    parent = "Sistema_Universitario"
    weight = 5
    [menu.main.params]
        external_link = true
[[menu.main]]
    identifier = "Órganos de coordinación y cooperación"
    name = "Órganos de coordinación y cooperación"
    url = "/sistema-universitario/organos-de-coordinacion"
    parent = "Sistema_Universitario"
    weight = 6
[[menu.main]]
    identifier = "Preguntas frecuentes"
    name = "Preguntas frecuentes"
    url = "/sistema-universitario/preguntas-frecuentes"
    parent = "Sistema_Universitario"
    weight =7
[[menu.main]]
    identifier = "Tablón de anuncios"
    name = "Tablón de anuncios"
    url = "/sistema-universitario/tablon_de_anuncios"
    parent = "Sistema_Universitario"
    weight =8
[[menu.main]]
    identifier = "Estadisticas"
    name = "Estadísticas"
    weight = 5
    [menu.main.params]
        identifier = 'menu5'
[[menu.main]]
    name = "Catálogo de datos"
    url = "/estadisticas/catalogo-datos"
    parent = "Estadisticas"
    weight = 1
[[menu.main]]
    name = "Publicaciones e informes"
    url = "/estadisticas/publicaciones-informes"
    parent = "Estadisticas"
    weight = 2
[[menu.main]]
    identifier = "Todas nuestras infografías"
    name = "Todas nuestras infografías"
    url = "/estadisticas/nuestras-infografias"
    parent = "Estadisticas"
    weight = 3
[[menu.main]]
    identifier = "Clasificaciones estadísticas universitarias"
    name = "Clasificaciones estadísticas universitarias"
    url = "/estadisticas/clasificaciones-estadisticas"
    parent = "Estadisticas"
    weight = 4
[[menu.main]]
    identifier = "Qué estudiar y dónde en la universidad (QEDU)"
    name = "Qué estudiar y dónde en la universidad (QEDU)"
    url = "/sistema-universitario/donde-estudiar/"
    parent = "Estadisticas"
    weight = 5
[[menu.main]]
    identifier = "Peticiones estadísticas"
    name = "Peticiones estadísticas"
    url = "/estadisticas/peticiones-estadisticas"
    parent = "Estadisticas"
    weight = 6
[[menu.main]]
    identifier = "Sistema Integrado de Información Universitaria"
    name = "Sistema Integrado de Información Universitaria"
    url = "/estadisticas/sistema-integrado"
    parent = "Estadisticas"
    weight = 7
[[menu.main]]
    identifier = "Prensa"
    name = "Prensa"
    url = "/noticias/"
    weight = 6
    [menu.main.params]
        identifier = 'menu6'
	
[[menu.main]]
    name = "Noticias"
    url = "/noticias"
    parent = "Prensa"
    weight = 1
[[menu.main]]
    name = "Agenda del Ministro"
    url = "/eventos"
    parent = "Prensa"
    weight = 2
[[menu.main]]
    name = "Contacto"
    url = "/prensa/contacto"
    parent = "Prensa"
    weight = 3
	
  [[menu.footer]]
    name = "Aviso legal"
    url = "/aviso-legal/"
    weight = 1
  [[menu.footer]]
    name = "Mapa Web"
    url = "/mapa-web/"
    weight = 2
  [[menu.footer]]
    name = "Información y atención al ciudadano"
    url = "/tu-administracion/informacion-y-atencion-al-ciudadano/"
    weight = 3
  [[menu.footer]]
    name = "Accesibilidad"
    url = "/accesibilidad/"
    weight = 4
# Languages
[languages]
  [languages.es]
      contentDir = 'content/es'
      languageName = 'Español'
      weight = 1
  [languages.en]
      contentDir = 'content/en'
      languageName = 'Inglés'
      weight = 2
  [languages.fr]
      contentDir = 'content/fr'
      languageName = 'Francés'
      weight = 3
  [languages.ca]
      contentDir = 'content/ca'
      languageName = 'Catalán'
      weight = 4
[languages.eu]
      contentDir = 'content/eu'
      languageName = 'Euskera'
      weight = 5
 [languages.ga]
      contentDir = 'content/ga'
      languageName = 'Gallego'
      weight = 6
 [languages.va]
      contentDir = 'content/va'
      languageName = 'Valenciá'
      weight = 7